version: "3.8"

services:
  postgresdb:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes: 
    - postgresdb:/data/postgres
    ports:
    - "5432:5432"
    restart: unless-stopped

volumes:
  postgresdb: