server:
  port: 5000
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieapp
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
